  
dist: trusty
language: java
jdk:
 - oraclejdk13

addons:
 sonarcloud:
  organization: "fra199889"
  token:
   secure: "d5fd090e1bf61de4d0ac2a03ec1453410526d34c"

script: 

- ant build
- sonar-scanner



















